# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  database: developmentdb
  username: root
  password: "@Sumanark123"
  host: localhost
  encoding: utf8

test:
  database: testdb
  adapter: mysql2
  encoding: utf8
  username: root
  password: "@Sumanark123"
  host: localhost

production:
  adapter: mysql2
  database: Railsdb
  username: root
  password: "@Sumanark123"
  host: localhost
  encoding: utf8
